# mlp net parameters
policy_file: "policies/isaacsim-basic-05-03-26.mnn"
num_observations: 45

active_joint_names:
  [
    "J00_HIP_PITCH_L",
    "J06_HIP_PITCH_R",
    "J01_HIP_ROLL_L",
    "J07_HIP_ROLL_R",
    "J02_HIP_YAW_L",
    "J08_HIP_YAW_R",
    "J03_KNEE_PITCH_L",
    "J09_KNEE_PITCH_R",
    "J04_ANKLE_PITCH_L",
    "J10_ANKLE_PITCH_R",
    "J05_ANKLE_ROLL_L",
    "J11_ANKLE_ROLL_R",
  ]

active_joint_idx:
  [0, 6, 1, 7, 2, 8, 3, 9, 4, 10, 5, 11]

num_include_obs_steps: 5

# observation parameters
observation_scale_angular_vel: 0.2
observation_scale_dof_pos: 1.0
observation_scale_dof_vel: 0.05
observation_clip: 100.0

# joint control parameters
action_clip: 100.0
default_joint_q:
  - [-0.24, 0.0, 0.0, 0.48, -0.24, 0.0]
  - [-0.24, 0.0, 0.0, 0.48, -0.24, 0.0]
  - [0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0]

joint_kp:
  - [114.5, 114.5, 99.0, 114.5, 99.0, 99.0]
  - [114.5, 114.5, 99.0, 114.5, 99.0, 99.0]
  - [99.0]
  - [99.0, 99.0, 99.0, 99.0, 99.0]
  - [99.0, 99.0, 99.0, 99.0, 99.0]
  - [99.0]

joint_kd:
  - [9.11, 9.11, 7.88, 9.11, 7.88, 7.88]
  - [9.11, 9.11, 7.88, 9.11, 7.88, 7.88]
  - [7.88]
  - [7.88, 7.88, 7.88, 7.88, 7.88]
  - [7.88, 7.88, 7.88, 7.88, 7.88]
  - [7.88]

action_scale:
  - [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  - [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

control_dt: 0.02

command_scale: [0.5, 0.5, 1.0]
transition_time: 0.5
